version: '3.3'

services:
   chromium_65:
      image: 'oldwebtoday/chromium:65'
      build:
        context: .
        args:
            CHROMIUM_VERSION: "65.0.3325.181-0ubuntu0.16.04.1"

        labels:
            "wr.version": "65"
            "wr.release": "2018-04-06"
            "wr.caps.flash": "1"
